---
- name: Deploy movie app
  hosts: webservers
  tasks:
    - name: Create directory /applications
      file:
        path: /applications
        state: directory 
        owner: srvadmin
        group: srvadmin
        mode: 0750
